spring:
   data:
        elasticsearch:
            cluster-name: docker-cluster #默认为elasticsearch
            cluster-nodes: 192.168.79.50:9200 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode（9200端口是http查询使用的。9300集群使用。这里使用9300.）
            properties:
                path:
                  logs: ./elasticsearch/log #elasticsearch日志存储目录
                  data: ./elasticsearch/data
   couchbase:
     env:
       timeouts:
         key-value: #elasticsearch数据存储目录


